### ISSUE TITLE
Cannot import name wavelet

### ISSUE THREAD

**Issue by Chenoachem** [SoFiA-Admin/SoFiA#170]
I have installed SoFiA and have it running the gui.  I have downloaded the tutorial data and running through the steps.  However, I keep getting the error:
Traceback (most recent call last):
  File "/opt/SoFiA-1.3.0/sofia_pipeline.py", line 23, in <module>
    from sofia import wavelet_finder
  File "/opt/SoFiA-1.3.0/sofia/wavelet_finder.py", line 4, in <module>
    from sofia import wavelet as wv
ImportError: cannot import name wavelet
Pipeline failed with exit code 1.

I have looked in the sofia folder and there is not a file or directory named "wavelet" there is one in the "src" a folder named 'wavelet".  Not sure if something moved or is there something missing.

**Comment by SoFiA-Admin** [comment]
Thanks for reporting that problem. There could be several reasons for this error message that you could try to investigate:

* Did you by any chance change your operating system or Python version lately and then reinstalled SoFiA? In this case there might be multiple conflicting installations in the `build` folder in your SoFiA installation directory, as the installation folder has the operating system and Python version encoded in its name. My recommendation in this case would be to delete the `build` folder altogether, rerun the `setup.py` script and then update your environment variables as directed at the end of the installation procedure. After this, SoFiA should be working as expected.
* In addition to that, if you are a Mac user, you could try installing the latest development version of SoFiA instead (from https://github.com/SoFiA-Admin/SoFiA/archive/master.zip), as we recently had to make a few changes due to people encountering installation problems on the latest Mac OS version.

Let me know if this resolves your problem. If not, we would have to dig deeper to figure out what else might have gone wrong.

**Comment by Chenoachem** [comment]
Thank you for your help.
- I have not recently changed any version of python or OS.  I have only version 2.7 on my computer.
- I am on a Mac and using Mojave version 10.14.6.  I have not upgraded to the newest version.
Is wavelet a program that is being called in or is it part of a library within python?  I couldn't find anything that was not installed on my system but maybe I am missing a library?

**Comment by SoFiA-Admin** [comment]
The wavelet module is part of SoFiA and contains the 2D-1D wavelet filter, so in principle it should be found as it comes with the installation files.

Did you test any of the two suggestions above, and did that help solve the problem? I would suggest to first try deleting the `build` folder, recompiling SoFiA and updating the relevant environment variables in your `.bashrc` or `.cshrc` file (or wherever else you have defined those) as directed by the installation script.

If that doesn’t resolve the problem, please try installing the latest SoFiA development version instead to see if that helps. If not, please let me know so we can continue investigating.

**Comment by Chenoachem** [comment]
I did follow your suggestions and have gone as far as deleting the install, making sure that the reference was removed from my bashrc, making sure it was removed from my $PATH, rebooting my computer and trying the whole install from scratch.  I still get the same error.  I have searched the download folders for a file named "wavelet" and have found only a folder in the src folder.  

I then tried removing all references again and downloading the development version 2.0.  However, with this version I could not even get the gui to open.  

I tried downloading the 1.3.0 version again through the CSIRO Supported Software portal, but I get the same error:

Traceback (most recent call last):
  File "/opt/SoFiA-1.3.0/sofia_pipeline.py", line 23, in <module>
    from sofia import wavelet_finder
  File "/opt/SoFiA-1.3.0/sofia/wavelet_finder.py", line 4, in <module>
    from sofia import wavelet as wv
ImportError: cannot import name wavelet
Pipeline failed with exit code 1.

**Comment by RussellJurek** [comment]
That looks like the wavelet module hasn't been built. Can you post your
build log?

**Comment by SoFiA-Admin** [comment]
As a temporary workaround, you could comment out line 23 of the `sofia_pipeline.py` script like such:

`# from sofia import wavelet_finder`

This should allow you to run SoFiA for as long as you don’t enable the 2D-1D wavelet filter. All the other modules should hopefully work.

Note that SoFIA 2 does not come with a GUI. The latest development version of SoFiA 1 can be obtained from https://github.com/SoFiA-Admin/SoFiA/archive/master.zip.

**Comment by Chenoachem** [comment]
Thank you for the help.  I realised that there were permissions errors on the build due to the settings on my computer.  I have fixed that and was able to build without any errors.  Now I no longer get the wavelet error.

I was able to successfully run the tutorial now.  Cheers.

**Comment by RussellJurek** [comment]
Excellent. If you don't mind, would you mind posting the steps you took and
the specific error messages in the build log. That'll be of great help to
other users in the long run.

**Comment by SoFiA-Admin** [comment]
Excellent, I am pleased to hear that the issue has been resolved.

**Comment by Chenoachem** [comment]
Unfortunately my issue was very specific to my institution and their policies. I am not sure it would help others.
